name: Cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: mutate
      run: |
        mkdir -p .cache
        date --iso-8601=s > .cache/date.txt
    - name: store into cache
      uses: actions/cache/save@v4
      with:
        path: .cache
        key: cache-${{ github.sha }}

