name: Test job/step failure

on:
  workflow_dispatch:
    inputs:
      result_string:
        description: 'String of 5 chars (T/F), e.g. "TTFFT"'
        required: true
        default: "TTTTT"

jobs:
  normal:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:0:1 }}" = "T" ]; then
            echo "Step 1 passed"
          else
            echo "Step 1 failed"
            exit 1
          fi
      - name: Step 2
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:1:1 }}" = "T" ]; then
            echo "Step 2 passed"
          else
            echo "Step 2 failed"
            exit 1
          fi
      - name: Step 3
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:2:1 }}" = "T" ]; then
            echo "Step 3 passed"
          else
            echo "Step 3 failed"
            exit 1
          fi
      - name: Step 4
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:3:1 }}" = "T" ]; then
            echo "Step 4 passed"
          else
            echo "Step 4 failed"
            exit 1
          fi
      - name: Step 5
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:4:1 }}" = "T" ]; then
            echo "Step 5 passed"
          else
            echo "Step 5 failed"
            exit 1
          fi

  continue-on-error:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        continue-on-error: true
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:0:1 }}" = "T" ]; then
            echo "Step 1 passed"
          else
            echo "Step 1 failed"
            exit 1
          fi
      - name: Step 2
        continue-on-error: true
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:1:1 }}" = "T" ]; then
            echo "Step 2 passed"
          else
            echo "Step 2 failed"
            exit 1
          fi
      - name: Step 3
        continue-on-error: true
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:2:1 }}" = "T" ]; then
            echo "Step 3 passed"
          else
            echo "Step 3 failed"
            exit 1
          fi
      - name: Step 4
        continue-on-error: true
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:3:1 }}" = "T" ]; then
            echo "Step 4 passed"
          else
            echo "Step 4 failed"
            exit 1
          fi
      - name: Step 5
        continue-on-error: true
        run: |
          sleep 10
          if [ "${{ github.event.inputs.result_string:4:1 }}" = "T" ]; then
            echo "Step 5 passed"
          else
            echo "Step 5 failed"
            exit 1
          fi
